### ISSUE TITLE
local variable 'key' referenced before assignment

### ISSUE THREAD

**Issue by gmariani** [pmdevita/SSA-ASStoVTT#1]
Tried to use it today and got this immediately.

```
Traceback (most recent call last):
  File "ssatovtt.py", line 263, in <module>
    convert(args.ssa, args.vtt)
  File "ssatovtt.py", line 20, in convert
    sections[key] = section
UnboundLocalError: local variable 'key' referenced before assignment
```

**Comment by gmariani** [comment]
Almost forgot, i'm running on Windows 10 Pro 2004 using Python 3.8.6

**Comment by pmdevita** [comment]
I somehow completely missed this until now, IDK if you care anymore but can you send me your subtitle file?

**Comment by gmariani** [comment]
Oof, that was quite a while ago. I forgot about this too. I don't think i have those files anymore. I think i just ended up switching to MKVToolNix to extract the subtitles and then manually convert them over using Subtitle Edit. If i do run into this again I'll let you know but it's so long ago all the files i had are long gone.

**Comment by pmdevita** [comment]
Alright cool. I guess I'll leave this open for now in case someone else can reproduce this
